a => a.date("claimReportedDate").validate(v => v != null && v != '' ? null : "not.empty")
                    .date("claimPaidDate")
                    .date("claimEndDate")
                    .number("claimAmount")
                    .datalist("currencies", d => d.toLinkedMap(["PLN","GBP","USD","EUR"]))
                    .dropdown("claimCurrency", "currencies")
                    .datalist("claimStatuses", d => d.toLinkedMap(["APPROVED", "REJECTED", "PENDING","NEW"]))
                    .dropdown("status", "claimStatuses").validate(v => v != null && v != '' ? null : "not.empty")
                    .text("description")
                    .manyToOne("policyId","policy")
                    .files("filesId", (f,r) => r.getFileDtos(f.entity), "image/png,image/jpeg,application/pdf")