a => a.datalist("clientTypes", d => d.toLinkedMap(["INDIVIDUAL", "CORPORATE"]))
                    .sectionWithDropdown("clientType", "clientTypes").additionalCss("clientTypeSection")
                    	.text("firstName").additionalCss("clientTypeSectionNode INDIVIDUAL")
                    	.text("lastName").additionalCss("clientTypeSectionNode INDIVIDUAL")
                    	.date("dateOfBirth").additionalCss("clientTypeSectionNode INDIVIDUAL")
                    	.text("gender").additionalCss("clientTypeSectionNode INDIVIDUAL")
                    .text("companyName").additionalCss("clientTypeSectionNode CORPORATE")
                    .text("companyLegalName").additionalCss("clientTypeSectionNode CORPORATE")
                    .text("email")
                    .text("address")
                    .text("contactPerson")
                    .text("contactAddress")
                    .text("billingAddress")
                    .text("contactNumber")
                    .datalist("clientStatuses", d => d.toLinkedMap(["Active", "Prospect", "Both"]))
                    .dropdown("clientStatus", "clientStatuses")
                    .files("filesId", (f,r) => r.getFileDtos(f.entity), "image/png,image/jpeg,application/pdf")

