a => a.text("endorsementId")
                    .text("policyId")
                    .date("endorsementDate")
                    .number("endorsementAmount")
                    .datalist("currencies", d => d.toLinkedMap(["PLN","GBP","USD","EUR","LBP"]))
                    .dropdown("endorsementCurrency", "currencies")
                    .text("coverageId")
                    .text("another")
                    .text("anothertwo")