a => a.date("date")
	.text("type")
    .text("number")
    .manyToOne("party","partyId")
    .text("category")
    .number("netTotal")
    .number("tax")
    .number("total")
    .manyToOne("constCenterId","costCenter")