a => a.text("partyId")
	.text("partyLegalName")
    .text("partyIntExtFlag")
    .text("partyCountryOfLocation")
    .text("partyOrganisationType")
    .text("partyTexNumber")
    .text("partytLegalAdress")