a => a.number("amount")
					.datalist("currencies", d => d.toLinkedMap(["PLN","GBP","USD","EUR"]))
                    .dropdown("amountCurrency", "currencies")
                    .date("paymentDueDate")
                    .date("paymentDate")
                    .datalist("paymentMethods", d => d.toLinkedMap(["CREDIT_CARD","BANK_TRANSFER","CASH","CHEQUE"]))
                    .dropdown("paymentMethod", "paymentMethods")
                    .datalist("paymentStatuses", d => d.toLinkedMap(["PAID", "UNPAID", "PENDING"]))
                    .dropdown("paymentStatus", "paymentStatuses").validate(v => v != null && v != '' ? null : "not.empty")
                    .manyToOne("policyId","policy")
                    .files("filesId", (f,r) => r.getFileDtos(f.entity), "image/png,image/jpeg,application/pdf")