a => a.text("address")
                    .text("city")
                    .text("state")
                    .text("zipCode")
                    .number("propertyValue")
                    .datalist("propertyTypes", d => d.toLinkedMap(["RESIDENTIAL", "COMMERCIAL", "INDUSTRIAL", "AGRICULTURAL", "MIXED_USE"]))
                    .dropdown("propertyType", "propertyTypes")
                    .manyToOne("policyId","policy")
                    .manyToOne("coverageId","coverage")
                    .text("geoportalId")
                    .files("filesId", (f,r) => r.getFileDtos(f.entity), "image/png,image/jpeg,application/pdf")