a => a.text("make")
                    .text("model")
                    .text("licensePlate")
                    .text("vin")
                    .number("year")
                    .text("color")
                    .manyToOne("policyId","policy")
                    .manyToOne("coverageId","coverage")
                    .files("filesId", (f,r) => r.getFileDtos(f.entity), "image/png,image/jpeg,application/pdf")