!!com.openkoda.service.export.dto.FormConversionDto
"code": "code/form/org_121/product.js"
"filterColumns": !!null "null"
"module": "core"
"name": "product"
"organizationId": !!int "121"
"readPrivilege": "manageOrgData"
"registerApiCrudController": !!bool "true"
"registerHtmlCrudController": !!bool "true"
"showOnOrganizationDashboard": !!bool "true"
"tableColumns": "product,productDescription,partyId"
"tableName": "dynamic_product"
"tableView": !!null "null"
"writePrivilege": "manageOrgData"
